# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d137fe6489fad8edbb0244bcb4fca1cf917d9819d1333e70c45dced6f7b79b87389cd6038ab89d45c84872b0a659fe43e13a282e15631d40ae820e6e996a0708

test:
  secret_key_base: e80c3022cc8c1022e471f8c907706d4fd05707f312db3dd958d37fa8d7c53d7fc2a78fece4a849366070698c17a1e5044c3923c3ac76fd529555286e9048626d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
